export {default as img1} from "./validator1.png"
export {default as img2} from "./validator2.png"
export {default as img3} from "./validator3.png"
export {default as img4} from "./validator4.png"
export {default as img5} from "./validator5.png"
export {default as img6} from "./validator6.png"
export {default as img7} from "./validator7.png"
export {default as img8} from "./validator8.png"
